import jsPDF from 'jspdf';

export interface ImpactReportData {
  quantity: number;
  productType: 'pencil' | 'notepad' | 'pen';
  custom: boolean;
  seeds: number;
  paper: number;
  co2: number;
  trees: number;
  children: number;
}

export function generateImpactReportPDF(data: ImpactReportData): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const brandGreen: [number, number, number] = [16, 185, 129];
  const dark: [number, number, number] = [9, 9, 11];
  const gray: [number, number, number] = [113, 113, 122];
  const white: [number, number, number] = [255, 255, 255];

  doc.setFillColor(...dark);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');

  doc.setTextColor(...white);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('MORIVERT', margin, y + 8);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...gray);
  doc.text('Write. Plant. Grow.', margin, y + 14);

  doc.setFontSize(8);
  doc.text('Impact Report', pageWidth - margin, y + 8, { align: 'right' });
  doc.text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), pageWidth - margin, y + 14, { align: 'right' });

  y += 24;

  doc.setDrawColor(40, 40, 45);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandGreen);
  doc.text('YOUR IMPACT SUMMARY', margin, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...gray);
  doc.setFontSize(8);
  const productLabel = data.productType === 'pencil' ? 'Pencils' : data.productType === 'notepad' ? 'Notepads' : 'Pens';
  doc.text(`Based on ${data.quantity.toLocaleString()} ${productLabel}${data.custom ? ' (customised)' : ''}`, margin, y);
  y += 10;

  const metrics = [
    { label: 'Seeds Planted', value: data.seeds.toLocaleString(), unit: '' },
    { label: 'Paper Saved', value: data.paper.toLocaleString(), unit: 'g' },
    { label: 'CO₂ Avoided', value: data.co2.toLocaleString(), unit: 'g' },
    { label: 'Trees Saved', value: data.trees.toLocaleString(), unit: '' },
    { label: 'Children Impacted', value: data.children.toLocaleString(), unit: '' },
  ];

  const colWidth = contentWidth / 2;
  metrics.forEach((m, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = margin + col * (colWidth + 8);
    const yy = y + row * 18;

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...white);
    doc.text(`${m.value}${m.unit}`, x, yy);

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...gray);
    doc.text(m.label.toUpperCase(), x, yy + 6);
  });

  y += 50;

  doc.setDrawColor(40, 40, 45);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFontSize(7);
  doc.setTextColor(...gray);
  doc.text('Generated by Morivert — Plantable stationery from Mauritius', margin, doc.internal.pageSize.getHeight() - 15);
  doc.text('morivert.io', pageWidth - margin, doc.internal.pageSize.getHeight() - 15, { align: 'right' });

  doc.save(`morivert-impact-report-${Date.now()}.pdf`);
}
